insert into  product ( product_name,  product_price, product_quantity) values('chocolates', 1.23, 10)
insert into  product ( product_name,  product_price, product_quantity) values('chiclets', 1.1, 11)
insert into  product ( product_name,  product_price, product_quantity) values('wafers', 1.1, 12)

insert into customer([customer_name],[address],[dob]) values ('dimitris', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('costas', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('nikos', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('petros', 'athina', '1960-02-01')
insert into customer([customer_name],[address],[dob]) values ('dionysis', 'lamia', '1999-02-06')
insert into customer([customer_name],[address],[dob]) values ('iakovos', 'patra', '1987-03-04')
insert into customer([customer_name],[address],[dob]) values ('periklis', 'athina', '1945-02-01')
insert into customer([customer_name],[address],[dob]) values ('thomas', 'lamia', '1934-02-06')
insert into customer([customer_name],[address],[dob]) values ('giannis', 'patra', '2000-03-04')
insert into customer([customer_name],[address],[dob]) values ('giorgos', 'athina', '2005-02-01')
insert into customer([customer_name],[address],[dob]) values ('faethon', 'lamia', '1950-02-06')
insert into customer([customer_name],[address],[dob]) values ('odysseas', 'patra', '1923-03-04')
insert into customer([customer_name],[address],[dob]) values ('sotiris', 'athina', '1980-02-01')
insert into customer([customer_name],[address],[dob]) values ('fivos', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('damianos', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('savvas', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('achilleas', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('stelios', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('vassilis', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('meletis', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('nikos', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('dimitris', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('sokratis', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('ilias', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('elpidoforos', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('panagiotis', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('iraclis', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('aimilios', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('frixos', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('anastasios', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('alkiviadis', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('aristotelis', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('athanasios', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('apostolis', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('vaggelis', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('timotheos', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('pavlos', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('petros', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('christoforos', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('frederic', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('efstathios', 'patra', '1985-03-04')
insert into customer([customer_name],[address],[dob]) values ('wilhem', 'athina', '1970-02-01')
insert into customer([customer_name],[address],[dob]) values ('thomas', 'lamia', '1980-02-06')
insert into customer([customer_name],[address],[dob]) values ('nikos', 'patra', '1985-03-04')

insert into customerorder ([date]  ,[customer_id]) values(getdate() , 1)
